version: '3.3'
services:
  pt-auth-service:
    network_mode: "host"
    container_name: pt-auth-service
    environment:
      TZ: Asia/Shanghai
    ports:
      - '8081:8081'
    build:
      context: ../pt-auth-service
      dockerfile: Dockerfile
